import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "t.jin_01's Insta(Login/Signup/Profile)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="font-sans">{children}</body>
    </html>
  );
}
